export const site = {
  name: "Tobias Meredith",
  tagline: "Melbourne Tattoo Artist",
  headline: "Melbourne's considered custom tattoo practice",
  description:
    "Tobias Meredith is a Melbourne tattoo artist specialising in custom fine line, blackwork, illustrative, ornamental, and geometric tattoos. View his portfolio and book a tattoo consultation in Melbourne, Australia.",
  url: "https://tobiasmeredith.com",
  locale: "en_AU",
  city: "Melbourne",
  region: "Victoria",
  country: "Australia",
  location: "Melbourne, Australia",
  email: "hello@tobiasmeredith.com",
  instagram: "https://instagram.com/tobiasmeredith",
  bookingNote:
    "Book a tattoo consultation with Tobias Meredith in Melbourne. Share a few details about your idea and he will reply to discuss design, sizing, placement, and availability.",
  keywords: [
    "Tobias Meredith",
    "Melbourne tattoo artist",
    "tattoo artist Melbourne",
    "Melbourne tattoos",
    "custom tattoos Melbourne",
    "fine line tattoo Melbourne",
    "blackwork tattoo Melbourne",
    "illustrative tattoo Melbourne",
    "ornamental tattoo Melbourne",
    "geometric tattoo Melbourne",
    "botanical tattoo Melbourne",
    "tattoo consultation Melbourne",
    "book tattoo Melbourne",
    "best tattoo artist Melbourne",
    "custom tattoo design Melbourne",
    "tattoo studio Melbourne",
    "private tattoo artist Melbourne",
  ],
} as const;

export const nav = [
  { href: "/#melbourne-tattoo-artist", label: "Artist" },
  { href: "/#tattoo-styles-melbourne", label: "Styles" },
  { href: "/#tattoo-studio-melbourne", label: "Studio" },
  { href: "/work", label: "Work" },
  { href: "/blog", label: "Blog" },
  { href: "/booking", label: "Contact" },
] as const;
